// professor.js
import React from 'react';
import { useRouter } from 'next/router';
import { CardCurso } from '@/components';
import { listaCursos } from '@/constants/data';
import Head from 'next/head';

const Professor = () => {
  const router = useRouter();
  const { id } = router.query;
  console.log('ID do Professor:', id);

  const selectedProfessor = listaCursos.find((professor) => professor.cod === id);

  if (!selectedProfessor) {
    return <p>Professor não encontrado.</p>;
  }

  return (
    <>
      <Head>
        <title>{selectedProfessor.prof}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="details">
          <h2 className="heading">{selectedProfessor.prof}</h2>
          <div className="box-container">
            {listaCursos
              .filter((curso) => curso.prof === selectedProfessor.prof)
              .map((curso, i) => (
                <CardCurso key={i} curso={curso} />
              ))}
          </div>
        </section>
      </main>
    </>
  );
};

export const getStaticPaths = async () => {
  return {
    paths: listaCursos.map((professor) => ({
      params: { id: professor.cod.toString() },
    })),
    fallback: false,
  };
};

export const getStaticProps = async ({ params }) => {
  const { id } = params;
  const selectedProfessor = listaCursos.find((professor) => professor.cod === id);

  return {
    props: {
      selectedProfessor,
    },
  };
};

export default Professor;