import { CardCurso } from '@/components'
import { useAppContext } from '@/context/appContext'
import { useCurso } from '@/hooks'
import Head from 'next/head'
import { useEffect } from 'react'

const cursos = () => {
  const { cursos } = useAppContext()
  const { listarCursos } = useCurso()

  useEffect(() => {
    listarCursos()
  }, [])

  return (
    <>
      <Head>
        <title>Cursos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="container" id="courses">
          <h2 className="heading">Nossos Cursos</h2>

          <div className="box-container">
            {cursos.map((curso, i) => (
              <CardCurso
                key={i}
                curso={curso}
              />
            ))}
          </div>
        </section>
      </main>
    </>
  )
}

export default cursos