import { CardCurso } from '@/components'
import { listaCursos } from '@/constants/data'
import Head from 'next/head'

const cursos = () => {
  return (
    <>
      <Head>
        <title>Cursos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="container" id="courses">
          <h2 className="heading">Nossos Cursos</h2>

          <div className="box-container">
            {listaCursos.map((curso, i) => (
              <CardCurso
                key={i}
                curso={curso}
              />
            ))}
          </div>
        </section>
      </main>
    </>
  )
}

export default cursos