import Head from 'next/head'

const cursos = () => {
  return (
    <>
      <Head>
        <title>Cursos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Cursos</h1>
      </main>
    </>
  )
}

export default cursos