import { categorias, topicos } from '@/constants/data'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Inglês Transforma</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div class="container">
          <div class="hero text-center">
            <h1 class="hero-title hidden">Bem-vindx!</h1>
          </div>
          <div class="gif">
            <img src="online.gif" alt="GIF Animado" width="90%" />
          </div>
        </div>

        <section class="container" id="quick-options">
          <h2 class="heading">Opções Rápidas</h2>

          <div class="box-container">
            <div class="box">
              <h3 class="title">Curtidas e Comentários</h3>
              <p class="likes">Total de curtidas : <span>25</span></p>
              <a href="#" class="btn btn-dark-blue">ver curtidas</a>
              <p class="likes">Total comentários : <span>12</span></p>
              <a href="#" class="btn btn-dark-blue">ver comentários</a>
              <p class="likes">Salvar playlists: <span>4</span></p>
              <a href="#" class="btn btn-dark-blue">ver playlists</a>
            </div>

            <div class="cards-options">
              <div className="box">
                <h3 class="title">Categorias em alta</h3>
                <div className="flex">
                  {categorias.map(({ nome }) => (
                    <a href="#"><span>{nome}</span></a>
                  ))}
                </div>
              </div>
            </div>

            <div class="cards-options">
              <div className="box">
                <h3 class="title">Tópicos Populares</h3>
                <div className="flex">
                  {topicos.map(({ nome }) => (
                    <a href="#"><span>{nome}</span></a>
                  ))}
                </div>
              </div>
            </div>

            <div class="box tutor">
              <h3 class="title">Torne-se um tutor</h3>
              <p>Você é apaixonado pelo inglês e deseja fazer a diferença
                na vida de outras pessoas? Torne-se um tutor e ajude outros na comunicação em inglês.</p>
              <a href="teachers.html" class="btn btn-dark-blue">Iniciar</a>
            </div>
          </div>
        </section>

        <section class="container" id="courses">
          <h2 class="heading">Nossos Cursos</h2>

          <div class="box-container">
          </div>
          <div class="mt-5 d-flex justify-content-center ">
            <a href="../cursos/cursos.html" class="btn btn-dark-blue">Ver mais</a>
          </div>
        </section>
      </main>
    </>
  )
}
