import { CardCurso } from '@/components'
import { categorias, listaCursos, topicos } from '@/constants/data'
import { useAppContext } from '@/context/appContext'
import { useCurso } from '@/hooks'
import Head from 'next/head'
import Link from 'next/link'
import { useEffect } from 'react'

export default function Home() {
  const { cursos } = useAppContext()
  const { listarCursos } = useCurso()
  useEffect(() => {
    listarCursos()
  }, [])


  return (
    <>
      <Head>
        <title>Inglês Transforma</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container">
          <div className="hero text-center">
            <h1 className="hero-title hidden">Bem-vindx!</h1>
          </div>
          <div className="gif">
            <img src="online.gif" alt="GIF Animado" width="90%" />
          </div>
        </div>

        <section className="container" id="quick-options">
          <h2 className="heading">Opções Rápidas</h2>

          <div className="box-container">
            <div className="box">
              <h3 className="title">Curtidas e Comentários</h3>
              <p className="likes">Total de curtidas : <span>25</span></p>
              <a href="#" className="btn btn-dark-blue">ver curtidas</a>
              <p className="likes">Total comentários : <span>12</span></p>
              <a href="#" className="btn btn-dark-blue">ver comentários</a>
              <p className="likes">Salvar playlists: <span>4</span></p>
              <a href="#" className="btn btn-dark-blue">ver playlists</a>
            </div>

            <div className="cards-options">
              <div className="box">
                <h3 className="title">Categorias em alta</h3>
                <div className="flex">
                  {categorias.map(({ nome, icone }, i) => (
                    <a href="#" key={i}>
                      {icone()}
                      <span>{nome}</span>
                    </a>
                  ))}
                </div>
              </div>
            </div>

            <div className="cards-options">
              <div className="box">
                <h3 className="title">Tópicos Populares</h3>
                <div className="flex">
                  {topicos.map(({ nome, icone }, i) => (
                    <a href="#" key={i}>
                      {icone()}
                      <span>{nome}</span>
                    </a>
                  ))}
                </div>
              </div>
            </div>

            <div className="box tutor">
              <h3 className="title">Torne-se um tutor</h3>
              <p>Você é apaixonado pelo inglês e deseja fazer a diferença
                na vida de outras pessoas? Torne-se um tutor e ajude outros na comunicação em inglês.</p>
              <a href="teachers.html" className="btn btn-dark-blue">Iniciar</a>
            </div>
          </div>
        </section>

        <section className="container" id="courses">
          <h2 className="heading">Nossos Cursos</h2>

          <div className="box-container">

            {cursos.map((curso, i) => (
              i < 4 &&
              <CardCurso
                key={i}
                curso={curso}
              />
            ))}
          </div>
          <div className="mt-5 d-flex justify-content-center ">
            <Link href={'cursos'} className="btn btn-dark-blue">Ver mais</Link>
          </div>
        </section>
      </main>
    </>
  )
}
