import Head from 'next/head'

const login = () => {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="form-container">
          <form action="../home/index.html" id="form">
            <h3>Login</h3>
            <label>Email</label>
            <input type="email" placeholder="hp@email.com" maxlength="100" className="box" id="inpEmail" required />
            <label>Senha</label>
            <input type="password" placeholder="Digite sua nova senha" maxlength="50" className="box" id="inpPassword" required />
            <button type="submit" className="btn btn-dark-blue" id="btnLogin">Login</button>
          </form>
        </section>
      </main>
    </>
  )
}

export default login