import React from 'react';
import Link from 'next/link';
import { CardProfessor } from '@/components'
import { listaCursos } from '@/constants/data'
import Head from 'next/head'

const professores = () => {
  return (
    <>
      <Head>
        <title>Professores</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="teachers">
          <h1 className="heading">Professores</h1>

          <div className="box-container">
            <div className="box offer">
              <h3 className="title">Se torne um tutor</h3>
              <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Laudantium, corporis?</p>
              <a href="" className="btn btn-dark-blue">Começar</a>
            </div>

            {listaCursos.map((professor, i) => (
              <Link href={`/professor/${professor.cod}`} key={i}>
                <CardProfessor professor={professor} />
              </Link>
            ))}

          </div>

        </section>
      </main>
    </>
  )
}

export default professores