import { CardSobre } from '@/components'
import { sobreCards } from '@/constants/data'
import Head from 'next/head'

const sobre = () => {
  return (
    <>
      <Head>
        <title>Sobre</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="heading">Quem somos</h1>
        <div className="container">
          <div className="row">
            {sobreCards.map((card, i) => (
              <CardSobre
                key={i}
                card={card}
              />
            ))}

          </div>
        </div>
      </main>
    </>
  )
}

export default sobre