import { Aluno, CardStatus, Professor } from '@/components'
import { useAppContext } from '@/context/appContext'
import Head from 'next/head'

import { FaHeart, FaBookmark, FaComments } from "react-icons/fa";


const usuario = () => {
  const { usuario, qtdCursos } = useAppContext()
  const { nome, user_role, imagem } = usuario
  return (
    <>
      <Head>
        <title>Usuario</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main id="usuario">
        <section className="profile">
          <h1 className="heading">Perfil</h1>

          <div className="details">
            <div className="user">
              <img
                src={imagem}
                alt={`Foto de ${nome}`}
                className='object-fit-cover'
              />
              <h3>{nome}</h3>
              <p className="text-capitalize text-center">{user_role.toLowerCase()}</p>
              <a href="../update/update.html" className="btn btn-dark-blue">Editar perfil</a>
            </div>
            <div className="box-container">
              <CardStatus texto={"Playlist criadas"} numero={qtdCursos} icon={FaBookmark} />
              <CardStatus texto={"Aulas curtidas"} numero={0} icon={FaHeart} />
              <CardStatus texto={"Comentarios"} numero={0} icon={FaComments} />
            </div>
          </div>


          <section id="courses">
            <h2 className="heading">Playlists</h2>
            <div className="box-container">
              {user_role === "ALUNO" ? <Aluno /> : <Professor />}
            </div>

          </section>

        </section>
      </main>
    </>
  )
}

export default usuario
