insert into Professores( nome, email, senha, cpf, data_nascimento, sexo, imagem, user_role) values ("Luna Lovegood", "luna@email.com", "123456", "12345678", "1996-02-04", "Feminino", "https://raw.githubusercontent.com/RabbitDeWitt/harry-potter-imgs/main/luna-lovegood.jpg", "PROFESSOR");
insert into Professores( nome, email, senha, cpf, data_nascimento, sexo, imagem, user_role) values ("Ron Weasley", "ron@email.com", "123456", "12378456", "1996-02-04", "Masculino", "https://raw.githubusercontent.com/RabbitDeWitt/harry-potter-imgs/main/ronald-weasley.jpg", "PROFESSOR");
insert into Professores( nome, email, senha, cpf, data_nascimento, sexo, imagem, user_role) values ("Albus Dumbledore", "albus@email.com", "123456", "34567812", "1996-02-04", "Masculino", "https://raw.githubusercontent.com/RabbitDeWitt/harry-potter-imgs/main/albus-dumbledore.jpg", "PROFESSOR");
insert into Professores( nome, email, senha, cpf, data_nascimento, sexo, imagem, user_role) values ("Hermione Granger", "hermione@email.com", "123456", "12367845", "1996-02-04", "Feminino", "https://raw.githubusercontent.com/RabbitDeWitt/harry-potter-imgs/main/hermione-granger.jpg", "PROFESSOR");
insert into Professores( nome, email, senha, cpf, data_nascimento, sexo, imagem, user_role) values ("Draco Malfoy", "draco@email.com", "123456", "67812345", "1996-02-04", "Masculino", "https://raw.githubusercontent.com/RabbitDeWitt/harry-potter-imgs/main/draco-malfoy.jpg", "PROFESSOR");
insert into Professores( nome, email, senha, cpf, data_nascimento, sexo, imagem, user_role) values ("Minerva McGonagall", "minerva@email.com", "123456", "12365485", "1996-02-04", "Feminino", "https://raw.githubusercontent.com/RabbitDeWitt/harry-potter-imgs/main/minerva-mcgonagall.jpg", "PROFESSOR");

insert into Cursos(nome, qtd_aulas, data_publicacao, data_fechamento, imagem, professor_id)values("Preparação - Exames de Proficiência",13,"2023-04-05","2023-06-05","https://raw.githubusercontent.com/squad-42/Desafio-Recode-Pro/main/assets/imgs/thumb-3.png",1);
insert into Cursos(nome, qtd_aulas, data_publicacao, data_fechamento, imagem,professor_id)values("Inglês para Negócios",13,"2023-03-05","2023-06-11","https://raw.githubusercontent.com/squad-42/Desafio-Recode-Pro/main/assets/imgs/thumb-2.png",2);
insert into Cursos(nome, qtd_aulas, data_publicacao, data_fechamento, imagem,professor_id)values("Inglês Geral",10,"2023-01-05","2023-07-13","https://raw.githubusercontent.com/squad-42/Desafio-Recode-Pro/main/assets/imgs/thumb-1.png",3);
insert into Cursos(nome, qtd_aulas, data_publicacao, data_fechamento, imagem,professor_id)values("Inglês Acadêmico",25,"2023-07-05","2023-12-30","https://raw.githubusercontent.com/squad-42/Desafio-Recode-Pro/main/assets/imgs/thumb-4.png",4);
insert into Cursos(nome, qtd_aulas, data_publicacao, data_fechamento, imagem,professor_id)values("Inglês para viagens",16,"2023-02-05","2023-07-13","https://raw.githubusercontent.com/squad-42/Desafio-Recode-Pro/main/assets/imgs/thumb-5.png",5);
insert into Cursos(nome, qtd_aulas, data_publicacao, data_fechamento, imagem,professor_id)values("Inglês Técnico para área de TI",12,"2023-06-05","2023-08-05","https://raw.githubusercontent.com/squad-42/Desafio-Recode-Pro/main/assets/imgs/thumb-6.png",6);