import { useRouter } from 'next/router';
import { CardAula } from '@/components';
import Link from 'next/link'
import { listaCursos } from '@/constants/data';
import Head from 'next/head';

const curso = () => {

  const router = useRouter();
  const { id } = router.query;
  console.log('ID do Curso:', id);

  const selectedCurso = listaCursos.find((curso) => curso.cod === id);

  if (!selectedCurso) {
    return <p>Curso não encontrado.</p>;
  }


  return (
    <>
      <Head>
        <title>{selectedCurso.nome}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="playlist">
          <h1 className="heading">Detalhes da playlist</h1>

          <div className="row">
            <div className="col">
              <form action="" method="post" className="save-list">
                <button type="submit"><i className="far fa-bookmark"></i><span>salvar playlist</span></button>
              </form>
              <div className="thumb">
                <span>{selectedCurso.numOfVid} vídeos</span>
                <img src={`../thumb-${selectedCurso.thumb}.png`} alt="" />
              </div>
            </div>

            <div className="col">
              <div className="tutor">
                <img src={`../pic-${selectedCurso.profPic}.jpg`} alt="" />
                <div>
                  <h3>{selectedCurso.prof}</h3>
                  <span>Professor</span>
                </div>
              </div>

              <div className="details">
                <h3>{selectedCurso.course}</h3>
                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti nostrum ipsum ut possimus veritatis
                  fuga!</p>
                <div className="date">
                  <i className="fas fa-calendar">
                    <span>{selectedCurso.date}</span>
                  </i>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="video-container">
          <h2 className="heading">Playlist</h2>

          <div className="box-container">
            {selectedCurso.aulas
              .map((aula, i) => (
                <Link href="../video" className="box">
                  <i className="fas fa-play"></i>
                  <img src={`../thumb-${aula.thumb}.png`} alt="" />
                  <span>Aula {i}</span>
                  <h3>{aula.course}</h3>
                </Link>
              ))}
          </div>
        </section>

      </main>
    </>
  )
}

export default curso